#
 # @file Makefile
 # @author Jugal Shah (shahjugalr@gmail.com)
 # @brief Contains implementation for building project with g++.
 # @version 0.1
 # @date 17/04/2022
 # 
 # @copyright Copyright (c) 2022
 # 
 #/

BUILD:
	g++ main.cpp -std=c++17 -o ../bin/main
RUN:
	../bin/main
CLEAN:
	rm ../bin/main

build:
	g++ main.cpp -std=c++17 ../bin/main
run:
	../bin/main
clean:
	rm ../bin/main